In [1]:
#import libraries
import numpy as np
import xarray as xr
import pandas as pd
import matplotlib.pyplot as plt
from matplotlib.dates import date2num

In [3]:
#import dataset aqua
ds = xr.open_dataset('West_Africa_aqua.nc')
da = ds.AOD_550_Dark_Target_Deep_Blue_Combined_Mean_Mean

In [23]:
#stacking the lon and lat as one
da_stacked = da.stack(points=['lat','lon'])


#converting the date to numbers for trends estimate

da_stacked['time']= date2num(pd.to_datetime(da_stacked.time.values))
da_stacked = da_stacked.dropna(dim = 'time')

In [25]:
#function to compute trend

def linear_trend(x):
    pf = np.polyfit(x.time, x, 1)
    
    return xr.DataArray(pf[0])


#apply the function to the stacked lonlat and apply the function to it
trends = da_stacked.groupby('points').apply(linear_trend)
trend_unstacked = trends.unstack('points')

In [26]:
trends

<xarray.DataArray (points: 1125, dim_0: 4)>
array([[-5.75500945e-06, -5.75500945e-06, -5.75500945e-06,
        -5.75500945e-06],
       [-4.46968671e-06, -4.46968671e-06, -4.46968671e-06,
        -4.46968671e-06],
       [-4.11588336e-06, -4.11588336e-06, -4.11588336e-06,
        -4.11588336e-06],
       ...,
       [-1.37671909e-05, -1.37671909e-05, -1.37671909e-05,
        -1.37671909e-05],
       [-1.04902609e-05, -1.04902609e-05, -1.04902609e-05,
        -1.04902609e-05],
       [-1.00481652e-05, -1.00481652e-05, -1.00481652e-05,
        -1.00481652e-05]])
Coordinates:
  * points          (points) MultiIndex
  - points_level_0  (points) float64 0.5 0.5 0.5 0.5 0.5 ... 24.5 24.5 24.5 24.5
  - points_level_1  (points) float64 -24.5 -23.5 -22.5 -21.5 ... 17.5 18.5 19.5
Dimensions without coordinates: dim_0

In [27]:
trend_unstacked

<xarray.DataArray (dim_0: 4, points_level_0: 25, points_level_1: 45)>
array([[[-5.75500945e-06, -4.46968671e-06, -4.11588336e-06, ...,
          1.29824435e-05,  1.63786834e-05,  1.69908258e-05],
        [-6.69028804e-06, -5.43519053e-06, -6.36624525e-06, ...,
          1.28978330e-05,  9.88331413e-06,  1.12088426e-05],
        [-6.94365426e-06, -7.76884431e-06, -5.63868486e-06, ...,
          1.09479509e-05,  9.54025090e-06,  7.60736094e-06],
        ...,
        [ 7.32220895e-07,  1.92324421e-08, -9.85770592e-07, ...,
         -6.64254708e-06, -4.27393860e-06, -1.65293487e-06],
        [ 1.36919767e-06,  1.08899422e-06, -3.50483775e-07, ...,
         -1.23665144e-05, -7.37169444e-06, -4.83935026e-06],
        [ 8.41953741e-07, -1.19199621e-06, -9.41323071e-07, ...,
         -1.37671909e-05, -1.04902609e-05, -1.00481652e-05]],

       [[-5.75500945e-06, -4.46968671e-06, -4.11588336e-06, ...,
          1.29824435e-05,  1.63786834e-05,  1.69908258e-05],
        [-6.69028804e-06, -5.43519053e-06, -6.36624525e-06, ...,
          1.28978330e-05,  9.88331413e-06,  1.12088426e-05],
        [-6.94365426e-06, -7.76884431e-06, -5.63868486e-06, ...,
          1.09479509e-05,  9.54025090e-06,  7.60736094e-06],
        ...,
        [ 7.32220895e-07,  1.92324421e-08, -9.85770592e-07, ...,
         -6.64254708e-06, -4.27393860e-06, -1.65293487e-06],
        [ 1.36919767e-06,  1.08899422e-06, -3.50483775e-07, ...,
         -1.23665144e-05, -7.37169444e-06, -4.83935026e-06],
        [ 8.41953741e-07, -1.19199621e-06, -9.41323071e-07, ...,
         -1.37671909e-05, -1.04902609e-05, -1.00481652e-05]],

       [[-5.75500945e-06, -4.46968671e-06, -4.11588336e-06, ...,
          1.29824435e-05,  1.63786834e-05,  1.69908258e-05],
        [-6.69028804e-06, -5.43519053e-06, -6.36624525e-06, ...,
          1.28978330e-05,  9.88331413e-06,  1.12088426e-05],
        [-6.94365426e-06, -7.76884431e-06, -5.63868486e-06, ...,
          1.09479509e-05,  9.54025090e-06,  7.60736094e-06],
        ...,
        [ 7.32220895e-07,  1.92324421e-08, -9.85770592e-07, ...,
         -6.64254708e-06, -4.27393860e-06, -1.65293487e-06],
        [ 1.36919767e-06,  1.08899422e-06, -3.50483775e-07, ...,
         -1.23665144e-05, -7.37169444e-06, -4.83935026e-06],
        [ 8.41953741e-07, -1.19199621e-06, -9.41323071e-07, ...,
         -1.37671909e-05, -1.04902609e-05, -1.00481652e-05]],

       [[-5.75500945e-06, -4.46968671e-06, -4.11588336e-06, ...,
          1.29824435e-05,  1.63786834e-05,  1.69908258e-05],
        [-6.69028804e-06, -5.43519053e-06, -6.36624525e-06, ...,
          1.28978330e-05,  9.88331413e-06,  1.12088426e-05],
        [-6.94365426e-06, -7.76884431e-06, -5.63868486e-06, ...,
          1.09479509e-05,  9.54025090e-06,  7.60736094e-06],
        ...,
        [ 7.32220895e-07,  1.92324421e-08, -9.85770592e-07, ...,
         -6.64254708e-06, -4.27393860e-06, -1.65293487e-06],
        [ 1.36919767e-06,  1.08899422e-06, -3.50483775e-07, ...,
         -1.23665144e-05, -7.37169444e-06, -4.83935026e-06],
        [ 8.41953741e-07, -1.19199621e-06, -9.41323071e-07, ...,
         -1.37671909e-05, -1.04902609e-05, -1.00481652e-05]]])
Coordinates:
  * points_level_0  (points_level_0) float64 0.5 1.5 2.5 3.5 ... 22.5 23.5 24.5
  * points_level_1  (points_level_1) float64 -24.5 -23.5 -22.5 ... 18.5 19.5
Dimensions without coordinates: dim_0

In [30]:
tre = trend_unstacked

<xarray.DataArray (dim_0: 4, points_level_0: 25, points_level_1: 45)>
array([[[-5.75500945e-06, -4.46968671e-06, -4.11588336e-06, ...,
          1.29824435e-05,  1.63786834e-05,  1.69908258e-05],
        [-6.69028804e-06, -5.43519053e-06, -6.36624525e-06, ...,
          1.28978330e-05,  9.88331413e-06,  1.12088426e-05],
        [-6.94365426e-06, -7.76884431e-06, -5.63868486e-06, ...,
          1.09479509e-05,  9.54025090e-06,  7.60736094e-06],
        ...,
        [ 7.32220895e-07,  1.92324421e-08, -9.85770592e-07, ...,
         -6.64254708e-06, -4.27393860e-06, -1.65293487e-06],
        [ 1.36919767e-06,  1.08899422e-06, -3.50483775e-07, ...,
         -1.23665144e-05, -7.37169444e-06, -4.83935026e-06],
        [ 8.41953741e-07, -1.19199621e-06, -9.41323071e-07, ...,
         -1.37671909e-05, -1.04902609e-05, -1.00481652e-05]],

       [[-5.75500945e-06, -4.46968671e-06, -4.11588336e-06, ...,
          1.29824435e-05,  1.63786834e-05,  1.69908258e-05],
        [-6.69028804e-06, -5.43519053e-06, -6.36624525e-06, ...,
          1.28978330e-05,  9.88331413e-06,  1.12088426e-05],
        [-6.94365426e-06, -7.76884431e-06, -5.63868486e-06, ...,
          1.09479509e-05,  9.54025090e-06,  7.60736094e-06],
        ...,
        [ 7.32220895e-07,  1.92324421e-08, -9.85770592e-07, ...,
         -6.64254708e-06, -4.27393860e-06, -1.65293487e-06],
        [ 1.36919767e-06,  1.08899422e-06, -3.50483775e-07, ...,
         -1.23665144e-05, -7.37169444e-06, -4.83935026e-06],
        [ 8.41953741e-07, -1.19199621e-06, -9.41323071e-07, ...,
         -1.37671909e-05, -1.04902609e-05, -1.00481652e-05]],

       [[-5.75500945e-06, -4.46968671e-06, -4.11588336e-06, ...,
          1.29824435e-05,  1.63786834e-05,  1.69908258e-05],
        [-6.69028804e-06, -5.43519053e-06, -6.36624525e-06, ...,
          1.28978330e-05,  9.88331413e-06,  1.12088426e-05],
        [-6.94365426e-06, -7.76884431e-06, -5.63868486e-06, ...,
          1.09479509e-05,  9.54025090e-06,  7.60736094e-06],
        ...,
        [ 7.32220895e-07,  1.92324421e-08, -9.85770592e-07, ...,
         -6.64254708e-06, -4.27393860e-06, -1.65293487e-06],
        [ 1.36919767e-06,  1.08899422e-06, -3.50483775e-07, ...,
         -1.23665144e-05, -7.37169444e-06, -4.83935026e-06],
        [ 8.41953741e-07, -1.19199621e-06, -9.41323071e-07, ...,
         -1.37671909e-05, -1.04902609e-05, -1.00481652e-05]],

       [[-5.75500945e-06, -4.46968671e-06, -4.11588336e-06, ...,
          1.29824435e-05,  1.63786834e-05,  1.69908258e-05],
        [-6.69028804e-06, -5.43519053e-06, -6.36624525e-06, ...,
          1.28978330e-05,  9.88331413e-06,  1.12088426e-05],
        [-6.94365426e-06, -7.76884431e-06, -5.63868486e-06, ...,
          1.09479509e-05,  9.54025090e-06,  7.60736094e-06],
        ...,
        [ 7.32220895e-07,  1.92324421e-08, -9.85770592e-07, ...,
         -6.64254708e-06, -4.27393860e-06, -1.65293487e-06],
        [ 1.36919767e-06,  1.08899422e-06, -3.50483775e-07, ...,
         -1.23665144e-05, -7.37169444e-06, -4.83935026e-06],
        [ 8.41953741e-07, -1.19199621e-06, -9.41323071e-07, ...,
         -1.37671909e-05, -1.04902609e-05, -1.00481652e-05]]])
Coordinates:
  * points_level_0  (points_level_0) float64 0.5 1.5 2.5 3.5 ... 22.5 23.5 24.5
  * points_level_1  (points_level_1) float64 -24.5 -23.5 -22.5 ... 18.5 19.5
Dimensions without coordinates: dim_0